language: objective-c
osx_image: xcode7.3
before_install:
- sudo gem install bundler
script:
- REPO_SLUG="$TRAVIS_REPO_SLUG" PULL_REQUEST="$TRAVIS_PULL_REQUEST" FORCE_CARTHAGE_VERSION=true
  script/cibuild
branches:
  only:
  - master
